baseURL = "https://poarthanarseus.github.io/"
title = "Westview Bridge Club"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
publishDir = "docs"
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Westview Bridge Club"
description = "Westview Bridge Club description"
keywords = [ "Blog", "Bridge", "Westview", "Club", "Tutorial" ]
author = "Arnold Yang"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/uploads/playing-cards.ico"
  favicon16x16 = "/uploads/playing-cards.ico"
  favicon32x32 = "/uploads/playing-cards.ico"
  apple_touch_icon = "/uploads/playing-cards.ico"
  safari_pinned_tab = "/uploads/playing-cards.ico"

  [params.label]
  text = "Westview Bridge Club"
  icon = "/uploads/playing-cards.ico"
  iconHeight = 35                 
  #icon = "/apple-touch-icon.png"
  #iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "♣ ♢ Westview Bridge Club ♡ ♠"
  Content = 'Contract Bridge is the ultimate partnership card game, where 4 players are dealt a deck a 52 cards equally. With only the information about their partners and opponents cards communicated through "bidding" on the trump suit at the start of the game, contract bridge is an ultimate strategic game, requiring cooperation, skill, calculation, and unlimited possibilities. It is one of the few games where the best AI are still worse than the best humans and the game has featured many regular playing celebrities like Bill Gates, Warren Buffett and astronaut Greg "Box" Johnson.'

  [[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/Wnnw7rhwpJ"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:arnold.tianyi.yang@gmail.com"

  [[params.socialIcons]]
  name = "Signup Forms"
  url = "https://docs.google.com/forms/d/e/1FAIpQLScOJSJKP9f-yOLxpUv7e3iwQ4V8V7P15oaALK2KxESDwtrmKg/viewform"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "How to Play Bridge"
name = "How to Play Bridge"
url = "/bridge-rules/"
weight = 10

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "Upcoming Events"
name = "Upcoming Events"
url = "/events/"
weight = 40

[markup]
unsafe = true

  [markup.highlight]
  noClasses = false
